# config.yaml
server:
  port: ":8080"

redis:
  address: "localhost:6379"
  password: ""
  db: 0

sqlite:
  path: "./llm_backend.db"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: 0  # 0 表示永久连接
jwt:
  secret: "S3cureK3y#2024!AIsafety"
